image: node:22-alpine

stages:
  - npm
  - audit
  - lint
  - build
  - test
  - deploy

npm:
  stage: npm
  script:
    - npm ci
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - .svelte-kit/
      - node_modules/

audit:
  stage: audit
  script:
    - npm audit --audit-level=moderate

lint:
  stage: lint
  script:
    - npm run lint
    - npm run check

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.52.0-noble
  script:
    - npm test

deploy_dev:
  stage: deploy
  environment:
    name: Development
  script:
    - echo "Deploying to DEV"
    - apk add lftp
    - lftp -c "open -u $FTP_USER_DEV,$FTP_PASS_DEV $FTP_HOST_DEV; mirror -Revp -X .ht* -P10 build/ ."
  only:
    refs:
      - main

deploy_staging:
  stage: deploy
  environment:
    name: Staging
  script:
    - echo "Deploying to STAGING"
    - apk add lftp
    - lftp -c "open -u $FTP_USER_STAGING,$FTP_PASS_STAGING $FTP_HOST_STAGING; mirror -Revp -X .ht* -P10 build/ ."
  only:
    refs:
      - staging

deploy_prod:
  stage: deploy
  environment:
    name: Production
  script:
    - echo "Deploying to PROD"
    - apk add lftp
    - lftp -c "open -u $FTP_USER_PROD,$FTP_PASS_PROD $FTP_HOST_PROD; mirror -Revp -X .ht* -P10 build/ ."
  only:
    refs:
      - release
