name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Release
    runs-on: docker

    container:
      image: ghcr.io/catthehacker/ubuntu:js-latest

    env:
      REGISTRY: code.d7c.de
      ACTIONS_USER: actions

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - run: npm install --no-save @semantic-release/git @semantic-release/changelog

      - run: |
          echo <<EOF >.releaserc
          {
            "branches": ["release"],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/npm",
              "@semantic-release/git"
            ]
          }
          EOF

      - run: ls -lha

      - id: semrel
        run: |
          SEMREL_OUTPUT=$(npx semantic-release)
          echo $SEMREL_OUTPUT
          RELEASE_VERSION=$(echo "$SEMREL_OUTPUT" | awk '/The next release version is/ { print $NF }')
          echo $RELEASE_VERSION
          {
            echo RELEASE_VERSION=$RELEASE_VERSION
            echo RELEASE_SHA=$(git rev-parse HEAD)
            echo VERSION_MAJOR=$(echo $RELEASE_VERSION | sed -r 's/([0-9]+)\.[0-9]+\.[0-9]+/\1/')
            echo VERSION_MAJOR_MINOR=$(echo $RELEASE_VERSION | sed -r 's/([0-9]+\.[0-9]+)\.[0-9]+/\1/')
          } >> $GITHUB_OUTPUT

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ACTIONS_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ steps.semrel.outputs.RELEASE_VERSION }}
            ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ steps.semrel.outputs.VERSION_MAJOR_MINOR }}
            ${{ env.REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ steps.semrel.outputs.VERSION_MAJOR }}
          build-args: |
            GITHUB_REF_NAME=""
            GITHUB_SHA=${{ env.GITHUB_SHA }}
            GITHUB_RELEASE_VERSION=${{ steps.semrel.outputs.RELEASE_VERSION }}

      - run: |
          mkdir -p dist/release
          cp README.md CHANGELOG.md dist/release/

      - id: changelog
        run: |
          {
            echo 'changelog<<EOF'
            awk '/^## /{ p++ } p == 2 { exit } p >= 1' CHANGELOG.md
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - uses: actions/forgejo-release@v2
        with:
          direction: upload
          url: ${{ env.GITHUB_SERVER_URL }}
          repo: ${{ env.GITHUB_REPOSITORY }}
          release-dir: dist/release
          tag: v${{ steps.semrel.outputs.RELEASE_VERSION }}
          sha: ${{ steps.semrel.outputs.RELEASE_SHA }}
          release-notes: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.FORGEJO_TOKEN }}
