apiVersion: apps/v1
kind: Deployment
metadata:
  name: danielhaus-de-dev
  namespace: danielhaus
  labels:
    app: danielhaus-de
    environment: development
spec:
  replicas: 1
  # securityContext:
  #runAsNonRoot: true
  #runAsUser: ?
  selector:
    matchLabels:
      app: danielhaus-de
      environment: development
  template:
    metadata:
      labels:
        app: danielhaus-de
        environment: development
    spec:
      containers:
        - name: danielhaus-de
          image: code.d7c.de/danielhaus/danielhaus.de:main-dc4b862-1785765873 # {"$imagepolicy": "danielhaus:danielhaus-de-dev"}
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 3000
          # securityContext:
          #   readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 10m
            limits:
              memory: '256Mi'
      imagePullSecrets:
        - name: org-registry-access-token
---
apiVersion: v1
kind: Service
metadata:
  name: danielhaus-de-dev
  namespace: danielhaus
  labels:
    app: danielhaus-de
    environment: development
spec:
  selector:
    app: danielhaus-de
    environment: development
  ports:
    - name: web
      port: 3000
      targetPort: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: danielhaus-de-dev
  namespace: danielhaus
  labels:
    app: danielhaus-de
    environment: development
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.className: traefik
    traefik.ingress.kubernetes.io/router.middlewares: danielhaus-danielhaus-de-dev-auth@kubernetescrd
spec:
  tls:
    - hosts:
        - danielhaus.de.dev.d7c.de
      secretName: danielhaus-de-dev-d7c-de-tls
  rules:
    - host: danielhaus.de.dev.d7c.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: danielhaus-de-dev
                port:
                  number: 3000
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: danielhaus-de-dev-credentials
  namespace: danielhaus
spec:
  encryptedData:
    users: AgAFSt64G2l9bm05JpkNPS8aYb99C9UsbeMOitfbqobp0dzExt0mOGqWAZwq9lRLW4ost7j/t/gbm4zv9/kGRWX/6Lzek/HxVyVVdgdwkjQ5dLSJesWpZmPwsqTi8PtgMtTDTwNwlvxPR8u+nN7B3fFo3rQim/djXH+32X3iIhAkdVX1FIhSO0BS+foJ5c2ZSOTXGi1nVYgQhtzmstN/uwlrfGAbt39D79xgfIyjLn2Q1bTnre8QiW7n+0trwFLNi/9dVoz2PdC/DwJ427LuqEYrFWGT9tXtRLn+pZBJAu4YFwCGqvK/8VdQ2rEYWMGXF09Gf2KhnCjUGlM5sfb6v6myjRrpkboBqewV/Mzi/APDk/3Skdx+79bSNd/SsfEGLPpRG7j7lj8U7aGIZm5dHMeR4nYmlZhvDK/o+L6+V4OAIbqIK+ra7cnLF6p1j6RSebIgiGdTEc2uSx8ghs7suC1y/IGdCBJALZ+Dhn3N5snMI776Fj8uWIzB77Jvb5cafnEQq3dp9FZR3Fub2jKVGAdd+d8gimJHfN9UY/u9oZwo7RhjgpuuJWulrGUc9CxmDP/OAAIu/2T+MzePkOd4J+uGlwdYOTE0y8uG8UGg/COz3SGjNdpKsRsHOcQ4unNVVBpYbx377lyrVmg+kzipZKpBHdY4u7AfqN5LPG2pn00rzdI8jrz87b1sKNzH7uZ8MRNpdoZ1+T7st8KYPhEBPPIAQk5A2Anl+IESIFnEdD8wBEZEVwv6Gebn6hlA2AX/
  template:
    metadata:
      name: danielhaus-de-dev-credentials
      namespace: danielhaus
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: danielhaus-de-dev-auth
  namespace: danielhaus
spec:
  basicAuth:
    secret: danielhaus-de-dev-credentials
    realm: 'danielhaus.de (dev)'
    removeHeader: true
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: danielhaus-de-dev
  namespace: danielhaus
spec:
  imageRepositoryRef:
    name: danielhaus.de
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
