apiVersion: apps/v1
kind: Deployment
metadata:
  name: danielhaus-de-dev
  namespace: danielhaus
  labels:
    app: danielhaus-de
    environment: development
spec:
  replicas: 1
  # securityContext:
  #runAsNonRoot: true
  #runAsUser: ?
  selector:
    matchLabels:
      app: danielhaus-de
      environment: development
  template:
    metadata:
      labels:
        app: danielhaus-de
        environment: development
    spec:
      containers:
        - name: danielhaus-de
          image: code.d7c.de/danielhaus/danielhaus.de:main-5d8fb5f-1772222900 # {"$imagepolicy": "danielhaus:danielhaus-de-dev"}
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 3000
          # securityContext:
          #   readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 10m
            limits:
              memory: '256Mi'
      imagePullSecrets:
        - name: org-registry-access-token
---
apiVersion: v1
kind: Service
metadata:
  name: danielhaus-de-dev
  namespace: danielhaus
  labels:
    app: danielhaus-de
    environment: development
spec:
  selector:
    app: danielhaus-de
    environment: development
  ports:
    - name: web
      port: 3000
      targetPort: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: danielhaus-de-dev
  namespace: danielhaus
  labels:
    app: danielhaus-de
    environment: development
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.className: traefik
    traefik.ingress.kubernetes.io/router.middlewares: danielhaus-danielhaus-de-dev-auth@kubernetescrd
spec:
  tls:
    - hosts:
        - danielhaus.de.dev.d7c.de
      secretName: danielhaus-de-dev-d7c-de-tls
  rules:
    - host: danielhaus.de.dev.d7c.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: danielhaus-de-dev
                port:
                  number: 3000
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: danielhaus-de-dev-credentials
  namespace: danielhaus
spec:
  encryptedData:
    users: AgAviDMvuDt+xCotzvJ1lZJMyH2xvkHZlhLQbG36rQKrDATRikhyTWJ+gVyOGC3LZxWjJzfAQBbo1NaA2ejPZT1jXtwL8yKB5J01DHkCV009eNVW6GzOAq4GbNWfPmFaOzIKin75td+1otPetcVTK3jgPOVGzVcM3nVrLwtTBCR/jcagPV35sxkhOePbA2xmw2nozdvItHUjo4XHKlTXmhI+0DUFUblCQyczVL9h6K0rA1c390LJ4wsPqTgN2j7H0Nno0sOo/9WP+i6zcPuRXL7M8cgpnvzYX7cgy1eGH70cy+AZXJMkraELYD3UF5Vjg1/6zhEODAKalnh2W/n1dMJtvMaHofYrNhUkvFG0zhWybbHhEYiwQ5Ysfvyz7M7//O49sIvhDNbOceKLRB1ZwfvkdLFbBn1KTsKNtud4o7ycg2ojDYNSdd+wZkBnTo6BjBZU/KAsnknG3Na2OilqI9LJID/nZdm+BV9V8/m1Y8MgBtD5icCAPCN6E31iLmiAStWHCxWkLNCffrEhNVmcba7C/wveVBuQvLlsdL+O3HPFQR9tb99xlZuZpO8Ks72to4p7bF1XNBLWuJ12nQd1Lip2q7zOE46Q5acDfD/EHTaOyB2JTk6AvsBYVZnOaEF284Ca7Vbcr6+uUgRCTdMKnRSuzYADFT9QRjr9Tf0xBXox/MOJaFxYccpxt+/FFHNgiwaADVLKBC01P14Y71aDiUlFcnR0BYSnL09cX2L5kyDSMClDS1sY1OGFGKtVyESi
  template:
    metadata:
      name: danielhaus-de-dev-credentials
      namespace: danielhaus
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: danielhaus-de-dev-auth
  namespace: danielhaus
spec:
  basicAuth:
    secret: danielhaus-de-dev-credentials
    realm: 'danielhaus.de (dev)'
    removeHeader: true
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: danielhaus-de-dev
  namespace: danielhaus
spec:
  imageRepositoryRef:
    name: danielhaus.de
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
