apiVersion: apps/v1
kind: Deployment
metadata:
  name: danielhaus-de-staging
  namespace: danielhaus
  labels:
    app: danielhaus-de
    environment: staging
spec:
  replicas: 1
  # securityContext:
  #runAsNonRoot: true
  #runAsUser: ?
  selector:
    matchLabels:
      app: danielhaus-de
      environment: staging
  template:
    metadata:
      labels:
        app: danielhaus-de
        environment: staging
    spec:
      containers:
        - name: danielhaus-de
          image: code.d7c.de/danielhaus/danielhaus.de:staging-30f7f69-1781476930 # {"$imagepolicy": "danielhaus:danielhaus-de-staging"}
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 3000
          # securityContext:
          #   readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 10m
            limits:
              memory: '256Mi'
      imagePullSecrets:
        - name: org-registry-access-token
---
apiVersion: v1
kind: Service
metadata:
  name: danielhaus-de-staging
  namespace: danielhaus
  labels:
    app: danielhaus-de
    environment: staging
spec:
  selector:
    app: danielhaus-de
    environment: staging
  ports:
    - name: web
      port: 3000
      targetPort: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: danielhaus-de-staging
  namespace: danielhaus
  labels:
    app: danielhaus-de
    environment: staging
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.className: traefik
    traefik.ingress.kubernetes.io/router.middlewares: danielhaus-danielhaus-de-staging-auth@kubernetescrd
spec:
  tls:
    - hosts:
        - danielhaus.de.staging.d7c.de
      secretName: danielhaus-de-staging-d7c-de-tls
  rules:
    - host: danielhaus.de.staging.d7c.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: danielhaus-de-staging
                port:
                  number: 3000
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: danielhaus-de-staging-credentials
  namespace: danielhaus
spec:
  encryptedData:
    users: AgCE571W/RIklSG+dp3Eza0NUuHnA3bSz1mWX30nF7gm72++ZCSX1MV8dbmzgCMS3/gPGdCXN+qBdFBsw0BBwFG9iRwEbi8Hhz7v0sPI/6Lz56pYu95+4g/tN6o5xWPR3Gk9FHXU0OCmOBJ5igCRUP2gdkQVpIgRtRD6ECkgyORDbw0S62rGtGiZh/TeJxwS/sBAsBXQNC1OUExPpqzV4fobV9WfxlekgadhCuEj14NDDs71epZ6UdMKpLlTKcofMSIdfaIAJkseVAA2Otzv3OIIfe2/CbvjSLiARsMfGuXRIK/qKEsN0EwA2kkTiyykOG7vcqMZJDmh+UGS9zX1zT8Ptntdp6qxvQVYssVvWRfvQhRgZ/Pi0xoPkKBIV1rcaUEXi6kbNiEBBdVa1qkmVZz8OlBiUod9u7/4MbfsiUe6InVE00H2KxTGLHrtuF4ve0iFGhbkhw9sBk8YT3EGZTAk2NHYlQWWVj2VzpGolJqnmDlDnJy0P4SnSa6q3YAFuMsgR9ZMULDe4ndfkuDeHNUvYP3hNX1igi2bDStZO6VIeV+8fCrCWi14lyADJsvmVi/wQE7YiRSmsX8RxeeR9DtzeUVNWsj3vr3JQd+Tus63I8K+HKkKVylMba5uqU+WfkpLKIozNL5Kp9/+jbKDHNymuSM1H2/u4pMDagkCdbEfcEIGLcE2/lAZcRvJUY4ZVgQCAdceTlHD2cFxnXiILK4xAcdKbYkkfGSfZfULe3q8J4kRH3a/OvqAv0mDPEBu
  template:
    metadata:
      name: danielhaus-de-staging-credentials
      namespace: danielhaus
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: danielhaus-de-staging-auth
  namespace: danielhaus
spec:
  basicAuth:
    secret: danielhaus-de-staging-credentials
    realm: 'danielhaus.de (staging)'
    removeHeader: true
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: danielhaus-de-staging
  namespace: danielhaus
spec:
  imageRepositoryRef:
    name: danielhaus.de
  filterTags:
    pattern: '^staging-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
